version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    platform: linux/amd64
    command: jekyll serve --force_polling --drafts
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle